### ISSUE TITLE
Adding comments before export does not compile properly

### ISSUE THREAD

**Issue by omar-codesenberg** [Draccoz/twc#116]
If you add a comment in an exported class which does not extend a polymer element and this comment is placed before the **export** keyword, the compiler does not remove the **export** keyword when it writes to the .html file.

ie.

```
//bar
export class Foo {

}
```

compiles down to:
```
<script>
  //bar
  export class Foo {}
</script>
```

The compiled version contains the export keyword when it should be removed.

**Comment by Draccoz** [comment]
Fixed by literally adding a single letter :D (+ tests). Published as `0.4.7-rc`.
