### ISSUE TITLE
transpiles relative import paths incorrectly

### ISSUE THREAD

**Issue by omar-codesenberg** [Draccoz/twc#131]
`import "../../styles/shared-styles.html";`
transpiles to:
`<link rel="import" href="../../styles/shared-styles.html.html">`

Note the extra file extension appended at the end of the file path incorrectly.

**Comment by Draccoz** [comment]
This was left as that, as the idea was that all the components are TS modules and thus should be imported without an extension. Thinking about it now, it actually makes sense that some use cases might contain local components (imported relatively) that are not TS based.
Just fixed it, I will release a new version this weekend (Christmas gift ^^).

**Comment by omar-codesenberg** [comment]
Thanks for the update as always and Happy Holidays!
