### ISSUE TITLE
Decorators are not properly processed when tsconfig.json is present

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#43]
When I merely added a `tsconfig.json` with empty `compilerOptions` section to my project, the output is not the same as when the config file is absent.

Instead of only the `Polymer()` call, the output JS also contains the `__decorate` function and it's being used as typescript does by default. For example with `@notify` instead of `notify: true`, I'm getting

```
__decorate([
  notify
], AgsForm.prototype, "value");        
```

**Comment by Draccoz** [comment]
Fixed this issue and #44, #45, #46 in #49 PR. Fixed by setting additional `experimentalDecorators` and `module` as fixed options in compiler and handling `tsconfig` without `compilerOptions` field.
