### ISSUE TITLE
Preserve documentation

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#47]
twc should preserve element and property documentation. For elements, [Polymer documentation](https://www.polymer-project.org/1.0/docs/tools/documentation#element-summaries) gives two possible ways: 

1. as HTML comment above `<dom-module>`
1. if absent, as JS comment before `Polymer()` call

With twc, there is no `<dom-module>`, just the template. It may work to always have just the JS comment, even when `<dom-module>` is used. If not, the comment will have to be moved from JS to HTML

Second, individual properties can be [documented](https://www.polymer-project.org/1.0/docs/tools/documentation#properties). Currently these comments are completely dropped by TypeScript compiler. They will have to be extracted from ts code and moved to the final output

**Comment by tpluscode** [comment]
It turns out that element-level docs almost work (#58). For this ticket, only property documentation remains. yay!

**Comment by Draccoz** [comment]
Element level docs are done, just not merged yet. I am working on property/method docs at this moment and I'm close to finishing :).

**Comment by Draccoz** [comment]
Documentation (jsDoc) handling should be fixed now. TWC now handles class-level, property-level and method-level jsDoc.
