### ISSUE TITLE
Simplify globbing pattern

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#50]
The command line accepts a glob pattern but it has to end with the extension like `twc ts/**/*.ts --out-dir dist`.

Would it be nice to make it just `twc ts/**`

**Comment by tpluscode** [comment]
I'd also make this explicit in the readme

**Comment by Draccoz** [comment]
Can't change it. Globs are expanded by terminal before command is even executed, so `twc` has no control over it.
