### ISSUE TITLE
Running for directory should preserve paths

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#51]
Maybe I'm doing something wrong, because I thought it worked before. I try running

```
twc ts/**/*.ts -out-dir js
```

With the `ts` folder structure like

```
/
|-- ts
    |-- my-app
        |-- my-app.ts
    |-- my-menu
        |-- my-menu.ts
```

I'm getting a flat structure as result where I'd expect it to resemble that above

```
/
|-- js
    |-- my-app.d.ts
    |-- my-app.html
    |-- my-menu.d.ts
    |-- my-menu.html
```

**Comment by Draccoz** [comment]
Would be handy if you checked previous versions if it worked before. Nevertheless, it's a bug, need to fix that :P.
