### ISSUE TITLE
Create PolymerTS compatible annotations

### ISSUE THREAD

**Issue by Draccoz** [Draccoz/twc#60]
Create set of annotations to map PolymerTS decorators. Properties not annoted as `@property` should not be registered within properties object.

**Comment by tpluscode** [comment]
Would this be the default or opt-in?

**Comment by Draccoz** [comment]
It will be imported just like now, but instead of `twc/annotations/polymer` it will be something like `twc/annotations/polymerts`.

**Comment by tpluscode** [comment]
> Properties not annoted as @property should not be registered within properties object.

I'm concerned about this sentence. What would be the output of:

``` ts
import { property } from t'wc/annotations/polymerts';
import { notify } from 'twc/annotations/polymer';

export class MyElement {
  
  @property({ notify: true });
  polymerTsProp: Object;

  @notify
  oldSchoolProp: Number;
}
```

Would the `oldSchoolProp` appear in the output or not?

**Comment by Draccoz** [comment]
All the decorators will be fetched from either polymer or polymerts annotations set. Fetching polymerts will automatically disable property auto registration so it works pretty much like PolymerTS. It will not, however, change how current twc annotations work.
