### ISSUE TITLE
twc fail when there are no methods

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#77]
Version `0.2.0-beta.1`

An empty element cannot be processed. `twc` fails with

```
\npm\node_modules\twc\src\parsers\DTSParser.js:120
        definition.class.methods.forEach(function (method) {
                                ^

TypeError: Cannot read property 'forEach' of undefined
```

**Comment by Draccoz** [comment]
This issue will be fixed once #73 is finished (I am currently working on it as it will make it easier to finish #39 and #48).
