### ISSUE TITLE
New prereleases don't work on Windows

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#91]
An issue I though was limited to my personal laptop looks like an issue with twc `0.3+`.

When I run `twc` I get this:

`/cygdrive/c/Users/tpluskiewicz/AppData/Roaming/npm/twc: line 12: /usr/bin/node: No such file or directory`

**Comment by Draccoz** [comment]
That's a shebang issue, apparently I made it for *unix only :/. Gonna fix it today.
